services:
  backend:
    build: ./ehr-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./ehr-backend
          target: /src

  frontend:
    build:
      context: ./ehr-frontend
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
